#NAME: CODY HUBBARD
#EMAIL: CodySpHubbard@gmail.com
#UID: 004843389

default:
	gcc -g -Wall -Wextra  lab1a.c -o lab1a
clean:
	@rm -f lab1a lab1a-004843389.tar.gz 
dist:
	@tar -czf lab1a-004843389.tar.gz lab1a.c Makefile README