#NAME: CODY HUBBARD
#EMAIL: CodySpHubbard@gmail.com
#UID: 004843389

default:
	gcc -Wall -Wextra -g -o lab3a lab3a.c
dist:
	tar -czf lab3a-004843389.tar.gz README Makefile lab3a.c ext2_fs.h
clean:
	@rm -rf lab3a
	@-rm -rf lab3a-004843389.tar.gz